spring.application.name=api-library

# Configurações do Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/api_library_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Regras de Negócio da Biblioteca
biblioteca.emprestimo.limite-livros=3
biblioteca.emprestimo.prazo-dias=7
biblioteca.emprestimo.multa-diaria=2.00
